apiVersion: v1
kind: Service
metadata:
  labels:
    name: app-service
  name: app-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    name: app-node
  type: clusterIP