apiVersion: v1
kind: Service
metadata:
  labels:
    name: front-service
  name: front-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    name: front-node
  type: LoadBalancer